[agent]
  interval = "5s"
  flush_interval = "5s"
  omit_hostname = true

[[inputs.netflow]]
  service_address = "udp://:2055"
  protocol = "netflow v5"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
